apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: atul
  labels:
    app: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dhaddu/front:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_APIHOSTPORT
            value: ae1b8e104e8464e44aa311de6c2d5547-708103701.ap-south-1.elb.amazonaws.com
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /ok
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
